p8105_hw6_sx2337
================
Shun Xie
2022-11-20

``` r
suppressMessages(library(tidyverse))
suppressMessages(library(dbplyr))
options(tibble.print_min = 5)
```

# Problem 1

``` r
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

    ## Registered S3 method overwritten by 'hoardr':
    ##   method           from
    ##   print.cache_info httr

    ## using cached file: C:\Users\ALIENW~1\AppData\Local/Cache/R/noaa_ghcnd/USW00094728.dly

    ## date created (size, mb): 2022-11-20 10:40:09 (8.443)

    ## file min/max dates: 1869-01-01 / 2022-11-30

for $r^2$

``` r
results_df = 
  weather_df %>% 
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    models = map(strap, ~ lm(tmax ~ tmin, data = .x)),
    results_r = map(models, broom::glance),
    results_beta = map(models, broom::tidy)) 
```

``` r
r_val_info = 
  results_df %>% 
  select(results_r) %>% 
  unnest()
```

    ## Warning: `cols` is now required when using unnest().
    ## Please use `cols = c(results_r)`

``` r
r_val_info %>% 
  ggplot(aes(x = r.squared)) + geom_density()
```

![](p8105_hw6_sx2337_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

``` r
r_val_info %>% 
  summarize(
    mean_Val = mean(r.squared),
    median_val = median(r.squared),
    se = sd(r.squared),
    "2.5-quantile" = mean(r.squared)+qnorm(0.025)*sd(r.squared),
    "97.5-quantile" = mean(r.squared)+qnorm(0.775)*sd(r.squared)
  )
```

    ## # A tibble: 1 × 5
    ##   mean_Val median_val      se `2.5-quantile` `97.5-quantile`
    ##      <dbl>      <dbl>   <dbl>          <dbl>           <dbl>
    ## 1    0.912      0.912 0.00856          0.895           0.918

R square is likely to be symmetrically distributed with mean 0.91 and
median 0.91.

The 2.5% quantile and 97.5% quantile is therefore: 0.894 to 0.918.

For log_value of beta_0 and beta_1:

``` r
logbeta_val_info = 
  results_df %>% 
  select(results_beta) %>% 
  unnest(results_beta) %>% 
  select(term, estimate) %>% 
  pivot_wider(
    names_from = term,
    values_from = estimate
  ) %>% 
  janitor::clean_names() %>% 
  unnest() %>% 
  mutate(logval = log(intercept+tmin))

logbeta_val_info %>% 
  ggplot(aes(x = logval)) + geom_density()
```

![](p8105_hw6_sx2337_files/figure-gfm/unnamed-chunk-6-1.png)<!-- -->

``` r
logbeta_val_info %>% 
  summarize(
    mean_Val = mean(logval),
    median_val = median(logval),
    se = sd(logval),
    "2.5-quantile" = mean(logval)+qnorm(0.025)*sd(logval),
    "97.5-quantile" = mean(logval)+qnorm(0.775)*sd(logval)
  )
```

    ## # A tibble: 1 × 5
    ##   mean_Val median_val     se `2.5-quantile` `97.5-quantile`
    ##      <dbl>      <dbl>  <dbl>          <dbl>           <dbl>
    ## 1     2.11       2.11 0.0291           2.05            2.13

log value of $log(\beta_0+\beta_1)$ is likely to be symmetrically
distributed with mean 2.11 and median 2.11.

The 2.5% quantile and 97.5% quantile is therefore: 2.053 to 2.132.

# Problem 2

In this question, will explore the homocides data in 50 large US cities.

``` r
homocide_data = read_csv("data/homicide-data.csv", show_col_types = FALSE) %>% 
  replace(is.na(.),0)
homocide_data
```

    ## # A tibble: 52,179 × 12
    ##   uid    repor…¹ victi…² victi…³ victi…⁴ victi…⁵ victi…⁶ city  state   lat   lon
    ##   <chr>    <dbl> <chr>   <chr>   <chr>   <chr>   <chr>   <chr> <chr> <dbl> <dbl>
    ## 1 Alb-0…  2.01e7 GARCIA  JUAN    Hispan… 78      Male    Albu… NM     35.1 -107.
    ## 2 Alb-0…  2.01e7 MONTOYA CAMERON Hispan… 17      Male    Albu… NM     35.1 -107.
    ## 3 Alb-0…  2.01e7 SATTER… VIVIANA White   15      Female  Albu… NM     35.1 -107.
    ## 4 Alb-0…  2.01e7 MENDIO… CARLOS  Hispan… 32      Male    Albu… NM     35.1 -107.
    ## 5 Alb-0…  2.01e7 MULA    VIVIAN  White   72      Female  Albu… NM     35.1 -107.
    ## # … with 52,174 more rows, 1 more variable: disposition <chr>, and abbreviated
    ## #   variable names ¹​reported_date, ²​victim_last, ³​victim_first, ⁴​victim_race,
    ## #   ⁵​victim_age, ⁶​victim_sex

Then, create a city_state variable to combine city and state together,
as well as a binary variable indicating solved and non-solved case.

``` r
homocide_data_new = 
  homocide_data %>%
  mutate(city_state = str_c(city, ", ", state)) %>% 
  mutate(Whether_solved = ifelse(homocide_data$disposition=='Closed without arrest' | homocide_data$disposition=='Open/No arrest',0,1))

homocide_data_new %>% 
  select(city_state, Whether_solved)
```

    ## # A tibble: 52,179 × 2
    ##   city_state      Whether_solved
    ##   <chr>                    <dbl>
    ## 1 Albuquerque, NM              0
    ## 2 Albuquerque, NM              1
    ## 3 Albuquerque, NM              0
    ## 4 Albuquerque, NM              1
    ## 5 Albuquerque, NM              0
    ## # … with 52,174 more rows
